import express from "express";
import { Sequelize, DataTypes, Op } from "sequelize";
import bodyParser from "body-parser";
import cors from "cors";
import { authenticateUser } from "./middleware/auth.js";
import familiesRouter from "./routes/familiesRouter.js";
import statusRouter from "./routes/statusRouter.js";
import companyRouter from "./routes/companyRouter.js";
import containerRouter from "./routes/containerRouter.js";
import itemRouter from "./routes/itemRouter.js";
import stock_detail_itemRouter from "./routes/stock_detail_itemRouter.js";
import current_inventory_itemRouter from "./routes/current_inventory_itemRouter.js";
import stock_itemRouter from "./routes/stock_itemRouter.js";
import userRouter from "./routes/userRouter.js";
import type_userRouter from "./routes/type_userRouter.js";
import measureRouter from "./routes/measureRouter.js";
import essential_oilRouter from "./routes/essential_oilRouter.js";
import departmentRouter from "./routes/departmentRouter.js";
import oil_inputRouter from "./routes/oil_inputRouter.js";
import stock_e_oilRouter from "./routes/stock_e_oilRouter.js";
import current_inventory_e_oilRouter from "./routes/current_inventory_e_oilRouter.js";
import stock_detail_e_oilRouter from "./routes/stock_detail_e_oilRouter.js";
import labelRouter from "./routes/labelRouter.js";
import bagRouter from "./routes/bagRouter.js";
import pakageRouter from "./routes/pakageRouter.js";
import label_inputRouter from "./routes/label_inputRouter.js";
import stock_labelRouter from "./routes/stock_labelRouter.js";
import stock_detail_labelRouter from "./routes/stock_detail_labelRouter.js";
import current_inventory_labelRouter from "./routes/current_inventory_labelRouter.js";
import stock_pakageRouter from "./routes/stock_pakageRouter.js";
import pakage_inputRouter from "./routes/pakage_inputRouter.js";
import current_inventory_pakageRouter from "./routes/current_inventory_pakageRouter.js";
import stock_detail_pakageRouter from "./routes/stock_detail_pakageRouter.js";
import stock_bagRouter from "./routes/stock_bagRouter.js";
import bag_inputRouter from "./routes/bag_inputRouter.js";
import current_inventory_bagRouter from "./routes/current_inventory_bagRouter.js";
import stock_detail_bagRouter from "./routes/stock_detail_bagRouter.js";
import type_inventoryRouter from "./routes/type_inventoryRouter.js";
import item_partRouter from "./routes/item_partRouter.js";
import type_rechargeRouter from "./routes/type_rechargeRouter.js";
import item_informationRouter from "./routes/item_informationRouter.js";
import made_itemRouter from "./routes/made_itemRouter.js";

import { db } from "./db/conn.js";

const router = express.Router();
const app = express();
const port = 3002;

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
const corsOptions = {
  origin: "*",
  optionsSuccessStatus: 200,
};
app.use(cors(corsOptions));

app.use("/api/", router);
app.use("/api/families", familiesRouter);
app.use("/api/status", statusRouter);
app.use("/api/company", companyRouter);
app.use("/api/container", containerRouter);
app.use("/api/item", itemRouter);
app.use("/api/stock_detail_item", stock_detail_itemRouter);
app.use("/api/current_inventory_item", current_inventory_itemRouter);
app.use("/api/stock_item", stock_itemRouter);
app.use("/api/user", userRouter);
app.use("/api/type_user", type_userRouter);
app.use("/api/measure", measureRouter);
app.use("/api/essential_oil", essential_oilRouter);
app.use("/api/department", departmentRouter);
app.use("/api/oil_input", oil_inputRouter);
app.use("/api/stock_e_oil", stock_e_oilRouter);
app.use("/api/current_inventory_e_oil", current_inventory_e_oilRouter);
app.use("/api/stock_detail_e_oil", stock_detail_e_oilRouter);
app.use("/api/label", labelRouter);
app.use("/api/bag", bagRouter);
app.use("/api/pakage", pakageRouter);
app.use("/api/label_input", label_inputRouter);
app.use("/api/stock_label", stock_labelRouter);
app.use("/api/stock_detail_label", stock_detail_labelRouter);
app.use("/api/current_inventory_label", current_inventory_labelRouter);
app.use("/api/stock_pakage", stock_pakageRouter);
app.use("/api/pakage_input", pakage_inputRouter);
app.use("/api/current_inventory_pakage", current_inventory_pakageRouter);
app.use("/api/stock_detail_pakage", stock_detail_pakageRouter);
app.use("/api/stock_bag", stock_bagRouter);
app.use("/api/bag_input", bag_inputRouter);
app.use("/api/current_inventory_bag", current_inventory_bagRouter);
app.use("/api/stock_detail_bag", stock_detail_bagRouter);
app.use("/api/type_inventory", type_inventoryRouter);
app.use("/api/item_part", item_partRouter);
app.use("/api/type_recharge", type_rechargeRouter);
app.use("/api/item_information", item_informationRouter);
app.use("/api/made_item", made_itemRouter);

app.listen(port, async () => {
  await db.sequelize;
  console.log(`Example app listening on port ${port}`);
});
